version: '2'

services:
  db:
    image: mysql:latest
    command: mysqld --user=root
    volumes:
      - ${MYSQL_DB_DIR}:/var/lib/mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: webserver
      MYSQL_USER: bammmotif_admin
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      bamm_net:
        ipv4_address: ${NETWORK_PREFIX}.2

  redis_celery:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - ${REDIS_DB_DIR}:/data
    networks:
      bamm_net:
        ipv4_address: ${NETWORK_PREFIX}.3

  celery:
    build: .
    command: celery --app=webserver.celery:app worker
    user: ${BAMM_USER_UID}
    volumes:
      - ${WEBSERVER_DIR}:/code
      - ${MEDIA_DIR}:/code/media
      - ${MOTIF_DB_DIR}:/motif_db
      - ${LOG_DIR}:/logs
    links:
      - redis_celery
      - db
    networks:
      bamm_net:
        ipv4_address: ${NETWORK_PREFIX}.4
    environment: &env_vars
        - DJANGO_DEBUG=${DJANGO_DEBUG}
        - BAMM_LOG_LEVEL=${BAMM_LOG_LEVEL}
        - SECRET_KEY=${SECRET_KEY}
        - ALLOWED_HOSTS=${ALLOWED_HOSTS}
        - DB_HOST=${DB_HOST}
        - DB_NAME=${DB_NAME}
        - DB_PORT=${DB_PORT}
        - DB_USER=${DB_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_STARTUP_DELAY_SECONDS=${MYSQL_STARTUP_DELAY_SECONDS}
        - EXAMPLE_MOTIF_DB=${EXAMPLE_MOTIF_DB}
        - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE}
        - MAX_UPLOAD_SIZE_ANONYMOUS=${MAX_UPLOAD_SIZE_ANONYMOUS}

  web:
    build: .
    command: /usr/local/bin/dumb-init -- ./run_web.sh
    user: ${BAMM_USER_UID}
    environment:
      - EXAMPLE_MOTIF_DB=${EXAMPLE_MOTIF_DB}
    volumes:
      - ${WEBSERVER_DIR}:/code
      - ${MEDIA_DIR}:/code/media
      - ${MOTIF_DB_DIR}:/motif_db
      - ${LOG_DIR}:/logs
    ports:
      - "10080:10080"
      - "587:587"
      - "465:465"
    links:
      - db
      - redis_celery
      - celery
    networks:
      bamm_net:
        ipv4_address: ${NETWORK_PREFIX}.5
    environment: *env_vars


networks:
  bamm_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${NETWORK_PREFIX}.0/24
        gateway: ${NETWORK_PREFIX}.1
